<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.1.0</Version>
    <!-- Manifest fields (see https://github.com/goatcorp/DalamudPackager/blob/827d88dc/DalamudPackager/DalamudPackager.cs#L420) -->
    <Author>Vibe Code</Author>
    <Name>JEBlock</Name>
    <Punchline>Jump/Emote Block (JEBlock) compliments Gagspeak. Lock your partner into an emote without forcing HARDCORE mode.</Punchline>
    <Description>When using Triggers or Puppeteer for emotes, your partner can escape by tapping jump, or performing a new /emote. This plugin blocks those actions when /wringhands is detected. You can only escape by moving your character (which may be denied, or locked, by the restriction from Gagspeak)</Description>
    <RepoUrl></RepoUrl>
    <Tags>JEBlock;plugin;gagspeak;</Tags>
  </PropertyGroup>

  <ItemGroup>
    <Content Include=".\Data\jeblock.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
