<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>1.1.0.0</Version>

    <Author>Beep Boop Bip ... Vibe Code</Author>
    <Name>JEBlock</Name>

    <Punchline>Jump/Emote Block (JEBlock) complements Gagspeak. Lock your partner into an emote without forcing HARDCORE mode.</Punchline>

    <Description>When using Triggers or Puppeteer for emotes, your partner may escape by tapping jump or performing a new /emote. This plugin blocks those requests if a user configured 'Loci' effect is detected.</Description>

    <RepoUrl>https://github.com/feral-src/jeblock</RepoUrl>

    <Tags>JEBlock;plugin;gagspeak</Tags>
  </PropertyGroup>

  <!--Loci.Api - lets JEBlock read Loci status effects via Dalamud IPC-->
  <ItemGroup>
    <ProjectReference Include="Submodules\LociAPI\Loci.Api.csproj" />
  </ItemGroup>
<ItemGroup>
  <Compile Remove="Submodules\**" />
</ItemGroup>
</Project>